apiVersion: apps/v1
kind: Deployment 
metadata:
  name: keycloak
  namespace: keyclock-poc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: keycloak
  template:
    metadata:
      labels:
        app: keycloak
    spec:
      containers: 
      - name: keycloak
        image: nginx
        ports:
        - containerPort: 80
