apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak
spec:
  replicas: 1
  selector:
    matchLabels:
      app: keycloak
  template:
    metadata:
      labels:
        app: keycloak
    spec:
      containers:
        - name: keycloak
          image: quay.io/keycloak/keycloak:24.0

          args:
            - start

          env:
            # DB CONFIG (สำคัญสุด)
            - name: KC_DB
              value: postgres

            - name: KC_DB_URL
              value: jdbc:postgresql://postgres:5432/keycloak

            - name: KC_DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: keycloak-secret
                  key: POSTGRES_USER

            - name: KC_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: keycloak-secret
                  key: POSTGRES_PASSWORD

            # ADMIN USER
            - name: KEYCLOAK_ADMIN
              valueFrom:
                secretKeyRef:
                  name: keycloak-secret
                  key: KEYCLOAK_ADMIN

            - name: KEYCLOAK_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: keycloak-secret
                  key: KEYCLOAK_ADMIN_PASSWORD

            # OpenShift / Route
            - name: KC_PROXY
              value: edge

            - name: KC_HOSTNAME
              value: keycloak-poc.apps.cluster.domain

          ports:
            - containerPort: 8080

          resources:
            requests:
              memory: "512Mi"
            limits:
              memory: "1Gi"

          readinessProbe:
            httpGet:
              path: /realms/master
              port: 8080
            initialDelaySeconds: 30
            timeoutSeconds: 5

          livenessProbe:
            httpGet:
              path: /realms/master
              port: 8080
            initialDelaySeconds: 60
            timeoutSeconds: 5
