apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres
spec:
  serviceName: postgres
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      securityContext:
        runAsUser: 26
        fsGroup: 26

      containers:
        - name: postgres
          image: registry.redhat.io/rhel8/postgresql-15:latest

          ports:
            - containerPort: 5432

          env:
            - name: POSTGRESQL_DATABASE
              value: keycloak

            - name: POSTGRESQL_USER
              valueFrom:
                secretKeyRef:
                  name: keycloak-secret
                  key: POSTGRES_USER

            - name: POSTGRESQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: keycloak-secret
                  key: POSTGRES_PASSWORD

          volumeMounts:
            - name: data
              mountPath: /var/lib/pgsql/data

  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 10Gi
